### PR TITLE
Spacy model

### PR DESCRIPTION
**Pull request by WanderingStar**
Work in Progress

### CODE REVIEW

**Comment by WanderingStar** [comment]
This successfully downloads and installs the model, but when we try to use the model in Jupyter, the kernel crashes:

```
import spacy
nlp = spacy.load("en_default")

doc = nlp("Husbands ask repeated resolved but laughter debating. She end cordial visitor noisier fat subject general picture.")
for s in doc.sents:
    print(s)
```
```
jupyter_1  | WARNING:root:kernel 4b5bc2e9-712a-410a-b684-e2d88cb72e46 restarted
```

**Comment by simonb83** [comment]
I rebuilt this morning with the full model and do not have any issues running the code:
 ````
doc = nlp("Husbands ask repeated resolved but laughter debating. She end cordial visitor noisier fat subject general picture.")
for s in doc.sents:
    print(s)
````

````
Husbands ask repeated resolved but laughter debating.
She end cordial visitor noisier fat subject general picture.
````

**Comment by simonb83** [comment]
Update: I rebuilt after including an additional module in requirements.txt, and now am also getting kernel restart errors, although I am not able to consistently reproduce them.
Sometimes it is when running `spacy.load("en_default")` but other times I can load the model but the kernel restarts while running subsequent cells.

I also tried importing the model as a module, but the outcome was the same:

````
import en_core_web_md
nlp = en_core_web_md.load()
````

````
jupyter_1  | [I 19:31:23.622 NotebookApp] KernelRestarter: restarting kernel (1/5)
````

**Comment by WanderingStar** [comment]
It turned out that the kernel errors were due to running out of memory. I increased the setting in the Docker preferences to 8GB and it's fine.

**Pull request merged**
