### PR TITLE
deal with case where url doesn't exist

### PR DESCRIPTION
**Pull request by simonb83**
Not sure whether or not this is the best way to handle it.

I first attempted with `try` `except` but couldn't suppress printing of the error message (at least in Jupyter).

However, from looking at docs it seems that if the url doesn't exist, then calling `download()` results in empty `html`.

### CODE REVIEW

**Comment by jlln** [comment]
I have noticed this too. It seems to be an issue with the newspaper library silently failing to download. There is a workaround of sorts described here https://github.com/codelucas/newspaper/issues/213

**Comment by georgerichardson** [comment]
@simonb83 Looks like a good enough workaround. Do you think we need to still fill in the dictionary fields with blanks?

**Comment by simonb83** [comment]
Hmm, yes I think you're right @georgerichardson , probably best for ensuring consistency down the line. I'll update.

**Comment by simonb83** [comment]
Resolves #2

**Pull request merged**
